services:
  # ravendb:
  #   image: "ravendb/ravendb:ubuntu-latest"
  #   environment:
  #     RAVEN_License_Eula_Accepted: "true"
  #     RAVEN_ARGS: "--Setup.Mode=None --Security.UnsecuredAccessAllowed=PublicNetwork" # why is this hack needed, @RavenDB?
  #     RAVEN_ServerUrl: "http://0.0.0.0:8080"
  #     RAVEN_ServerUrl_Tcp: "tcp://0.0.0.0:38888"
  #   ports:
  #     - "8080:8080"
  # couchdb:
  #   image: "couchdb:latest"
  #   ports:
  #     - "5984:5984"
  #   volumes:
  #     - ./local.ini:/opt/couchdb/etc/local.ini
  rethinkdb:
    image: "rethinkdb:2.4.4-bookworm-slim"
    ports:
      - "8080:8080"
      - "28015:28015"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  lavalink:
    image: "ghcr.io/lavalink-devs/lavalink:0aa718c-alpine"
    environment:
      SERVER_PORT: 2334
      LAVALINK_SERVER_PASSWORD: foo
    ports:
      - "2334:2334"
